# Generated by Django 5.1.2 on 2024-11-07 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart_item_owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="people.people",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
