# Generated by Django 5.1.2 on 2024-11-09 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("product", "0002_remove_cartitem_cart_cartitem_cart_item_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_reviews",
                to="people.people",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_products",
                to="people.people",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewed_products",
                to="product.product",
            ),
        ),
    ]
