# Generated by Django 5.1.2 on 2024-11-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_item", "0002_alter_cartitem_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
